# nvidia/cuda image
services:
  huggingface:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${workspace}:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    #Enable Nvidia device access
    #see: https://docs.docker.jp/compose/gpu-support.html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

